apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chaosguard.fullname" . }}-secrets
  namespace: {{ include "chaosguard.namespace" . }}
  labels:
    {{- include "chaosguard.labels" . | nindent 4 }}
type: Opaque
data:
  JWT_SECRET: {{ .Values.secrets.jwtSecret | quote }}
  POSTGRES_USERNAME: {{ .Values.secrets.postgres.username | quote }}
  POSTGRES_PASSWORD: {{ .Values.secrets.postgres.password | quote }}
