package com.chaosguard.service;

import com.chaosguard.model.Finding;
import com.chaosguard.model.GeneratedFix;
import com.chaosguard.model.Scan;
import com.chaosguard.repository.FindingRepository;
import com.chaosguard.repository.GeneratedFixRepository;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.kohsuke.github.*;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;

import java.io.IOException;
import java.util.*;
import java.util.stream.Collectors;

@Service
@RequiredArgsConstructor
@Slf4j
public class GitHubService {

    private final ScanService scanService;
    private final FindingRepository findingRepository;
    private final GeneratedFixRepository generatedFixRepository;

    @Value("${chaosguard.github.token:}")
    private String githubToken;

    public List<Map<String, Object>> createIssues(UUID scanId) throws IOException {
        Scan scan = scanService.getScan(scanId);
        List<Finding> findings = findingRepository.findByScanIdOrderBySeverity(scanId);

        if (findings.isEmpty()) {
            return Collections.emptyList();
        }

        GitHub github = createGitHubClient();
        GHRepository repo = getRepository(github, scan.getRepoUrl());

        List<Map<String, Object>> createdIssues = new ArrayList<>();

        for (Finding finding : findings) {
            try {
                String title = String.format("[%s] %s - %s",
                        finding.getSeverity().toUpperCase(),
                        finding.getVulnerabilityType(),
                        finding.getTitle());

                StringBuilder body = new StringBuilder();
                body.append("## ChaosGuard Security Finding\n\n");
                body.append("**Severity:** ").append(finding.getSeverity()).append("\n");
                body.append("**Type:** ").append(finding.getVulnerabilityType()).append("\n");
                body.append("**File:** `").append(finding.getFilePath()).append("`\n");

                if (finding.getLineStart() != null) {
                    body.append("**Lines:** ").append(finding.getLineStart());
                    if (finding.getLineEnd() != null) {
                        body.append("-").append(finding.getLineEnd());
                    }
                    body.append("\n");
                }

                if (finding.getCweId() != null) {
                    body.append("**CWE:** ").append(finding.getCweId()).append("\n");
                }

                if (finding.getCvssScore() != null) {
                    body.append("**CVSS Score:** ").append(finding.getCvssScore()).append("\n");
                }

                body.append("\n### Description\n\n").append(finding.getDescription()).append("\n");

                if (finding.getCodeSnippet() != null) {
                    body.append("\n### Vulnerable Code\n\n```\n")
                        .append(finding.getCodeSnippet())
                        .append("\n```\n");
                }

                if (finding.getRemediation() != null) {
                    body.append("\n### Remediation\n\n").append(finding.getRemediation()).append("\n");
                }

                body.append("\n---\n*Generated by ChaosGuard AI*");

                List<String> labels = new ArrayList<>();
                labels.add("security");
                labels.add("chaosguard");
                labels.add("severity:" + finding.getSeverity().toLowerCase());

                GHIssueBuilder issueBuilder = repo.createIssue(title)
                        .body(body.toString());

                for (String label : labels) {
                    ensureLabelExists(repo, label);
                    issueBuilder.label(label);
                }

                GHIssue issue = issueBuilder.create();

                Map<String, Object> issueInfo = new HashMap<>();
                issueInfo.put("issueNumber", issue.getNumber());
                issueInfo.put("issueUrl", issue.getHtmlUrl().toString());
                issueInfo.put("findingId", finding.getId().toString());
                issueInfo.put("title", title);
                createdIssues.add(issueInfo);

                log.info("Created GitHub issue #{} for finding {}", issue.getNumber(), finding.getId());

            } catch (Exception e) {
                log.error("Failed to create issue for finding {}: {}", finding.getId(), e.getMessage());
                Map<String, Object> errorInfo = new HashMap<>();
                errorInfo.put("findingId", finding.getId().toString());
                errorInfo.put("error", e.getMessage());
                createdIssues.add(errorInfo);
            }
        }

        return createdIssues;
    }

    public List<Map<String, Object>> createPullRequests(UUID scanId) throws IOException {
        Scan scan = scanService.getScan(scanId);
        List<GeneratedFix> fixes = generatedFixRepository.findByScanId(scanId);

        if (fixes.isEmpty()) {
            return Collections.emptyList();
        }

        GitHub github = createGitHubClient();
        GHRepository repo = getRepository(github, scan.getRepoUrl());

        List<Map<String, Object>> createdPRs = new ArrayList<>();

        // Gate PR creation based on sandbox validation results (Task 4d)
        // syntax_valid=false → create issue only (no PR)
        // tests_pass=false → draft PR with warning label
        // tests_pass=true → normal PR
        List<GeneratedFix> prEligible = fixes.stream()
                .filter(fix -> {
                    Map<String, Object> meta = fix.getMetadata();
                    if (meta == null) return true;
                    Object syntaxValid = meta.get("syntax_valid");
                    // If syntax check explicitly failed, skip PR
                    return syntaxValid == null || Boolean.TRUE.equals(syntaxValid);
                })
                .collect(Collectors.toList());

        if (prEligible.isEmpty()) {
            log.info("No fixes eligible for PR (all failed syntax validation), creating issues instead for scan {}", scanId);
            return createIssues(scanId);
        }

        Map<String, List<GeneratedFix>> fixesByFile = prEligible.stream()
                .collect(Collectors.groupingBy(GeneratedFix::getFilePath));

        for (Map.Entry<String, List<GeneratedFix>> entry : fixesByFile.entrySet()) {
            String filePath = entry.getKey();
            List<GeneratedFix> fileFixes = entry.getValue();

            try {
                String branchName = String.format("chaosguard/fix-%s-%s",
                        scanId.toString().substring(0, 8),
                        filePath.replaceAll("[^a-zA-Z0-9]", "-"));

                String defaultBranch = repo.getDefaultBranch();
                GHRef defaultRef = repo.getRef("heads/" + defaultBranch);
                String sha = defaultRef.getObject().getSha();

                repo.createRef("refs/heads/" + branchName, sha);

                GHContent content = repo.getFileContent(filePath, defaultBranch);
                String currentContent = new String(content.read().readAllBytes());

                String updatedContent = currentContent;
                for (GeneratedFix fix : fileFixes) {
                    if (fix.getOriginalCode() != null && fix.getFixedCode() != null) {
                        updatedContent = updatedContent.replace(fix.getOriginalCode(), fix.getFixedCode());
                    }
                }

                String commitMessage = String.format("[ChaosGuard] Fix %d vulnerabilities in %s",
                        fileFixes.size(), filePath);

                repo.createContent()
                        .path(filePath)
                        .content(updatedContent)
                        .message(commitMessage)
                        .sha(content.getSha())
                        .branch(branchName)
                        .commit();

                StringBuilder prBody = new StringBuilder();
                prBody.append("## ChaosGuard Security Fixes\n\n");
                prBody.append("This PR contains automated fixes for security vulnerabilities ");
                prBody.append("detected by ChaosGuard AI.\n\n");
                prBody.append("### Fixed Vulnerabilities\n\n");

                for (GeneratedFix fix : fileFixes) {
                    prBody.append("- **").append(fix.getFilePath()).append("**: ")
                          .append(fix.getExplanation()).append("\n");
                }

                prBody.append("\n### Review Notes\n\n");
                prBody.append("Please review the changes carefully before merging.\n");
                prBody.append("\n---\n*Generated by ChaosGuard AI*");

                String prTitle = String.format("[ChaosGuard] Security fixes for %s", filePath);

                GHPullRequest pr = repo.createPullRequest(
                        prTitle,
                        branchName,
                        defaultBranch,
                        prBody.toString());

                // Add warning label if tests didn't pass
                List<String> prLabels = new ArrayList<>(List.of("security", "chaosguard", "auto-fix"));
                boolean allTestsPass = fileFixes.stream().allMatch(fix -> {
                    Map<String, Object> meta = fix.getMetadata();
                    if (meta == null) return false;
                    return Boolean.TRUE.equals(meta.get("tests_pass"));
                });
                if (!allTestsPass) {
                    prLabels.add("needs-review");
                }
                for (String label : prLabels) {
                    ensureLabelExists(repo, label);
                }
                pr.setLabels(prLabels.toArray(new String[0]));

                Map<String, Object> prInfo = new HashMap<>();
                prInfo.put("prNumber", pr.getNumber());
                prInfo.put("prUrl", pr.getHtmlUrl().toString());
                prInfo.put("filePath", filePath);
                prInfo.put("fixCount", fileFixes.size());
                prInfo.put("branch", branchName);
                createdPRs.add(prInfo);

                log.info("Created draft PR #{} for file {}", pr.getNumber(), filePath);

            } catch (Exception e) {
                log.error("Failed to create PR for file {}: {}", filePath, e.getMessage());
                Map<String, Object> errorInfo = new HashMap<>();
                errorInfo.put("filePath", filePath);
                errorInfo.put("error", e.getMessage());
                createdPRs.add(errorInfo);
            }
        }

        return createdPRs;
    }

    private GitHub createGitHubClient() throws IOException {
        if (githubToken == null || githubToken.isBlank()) {
            throw new IllegalStateException("GitHub token is not configured");
        }
        // Copy token to local var and avoid logging it
        String token = githubToken;
        try {
            return new GitHubBuilder()
                    .withOAuthToken(token)
                    .build();
        } catch (IOException e) {
            // Mask token in error messages — show only last 4 chars
            String masked = "****" + (token.length() > 4 ? token.substring(token.length() - 4) : "");
            throw new IOException("GitHub authentication failed (token: " + masked + "): " + e.getMessage(), e);
        }
    }

    private GHRepository getRepository(GitHub github, String repoUrl) throws IOException {
        String repoFullName = extractRepoFullName(repoUrl);
        return github.getRepository(repoFullName);
    }

    private String extractRepoFullName(String repoUrl) {
        String cleaned = repoUrl
                .replace("https://github.com/", "")
                .replace("http://github.com/", "")
                .replace("git@github.com:", "")
                .replace(".git", "");

        if (cleaned.endsWith("/")) {
            cleaned = cleaned.substring(0, cleaned.length() - 1);
        }

        return cleaned;
    }

    private void ensureLabelExists(GHRepository repo, String labelName) {
        try {
            repo.getLabel(labelName);
        } catch (IOException e) {
            try {
                String color = switch (labelName) {
                    case "severity:critical" -> "B60205";
                    case "severity:high" -> "D93F0B";
                    case "severity:medium" -> "FBCA04";
                    case "severity:low" -> "0E8A16";
                    case "security" -> "EE0701";
                    case "chaosguard" -> "5319E7";
                    case "auto-fix" -> "1D76DB";
                    default -> "EDEDED";
                };
                repo.createLabel(labelName, color);
            } catch (IOException ex) {
                log.warn("Could not create label {}: {}", labelName, ex.getMessage());
            }
        }
    }
}
